// -------------------------------------------------------//
//
// SHAMROCK code for hydrodynamics
// Copyright(C) 2021-2023 Timothée David--Cléris <timothee.david--cleris@ens-lyon.fr>
// Licensed under CeCILL 2.1 License, see LICENSE for more information
//
// -------------------------------------------------------//

#pragma once

/**
 * @file DataNode.hpp
 * @author Timothée David--Cléris (timothee.david--cleris@ens-lyon.fr)
 * @brief This file hold the definitions for a test DataNode
 */

#include "shambase/aliases_float.hpp"
#include "shambase/aliases_int.hpp"
#include <string>
#include <vector>

namespace shamtest::details {

    /// Data node generated by the test
    struct DataNode {
        std::string name;      ///< Name of the data node
        std::vector<f64> data; ///< Held data

        /// Serialize the assertion in JSON
        std::string serialize_json();
        /// Serialize the assertion in binary format
        void serialize(std::basic_stringstream<byte> &stream);
        /// DeSerialize the assertion from binary format
        static DataNode deserialize(std::basic_stringstream<byte> &reader);
    };
} // namespace shamtest::details
