// -------------------------------------------------------//
//
// SHAMROCK code for hydrodynamics
// Copyright(C) 2021-2023 Timothée David--Cléris <timothee.david--cleris@ens-lyon.fr>
// Licensed under CeCILL 2.1 License, see LICENSE for more information
//
// -------------------------------------------------------//

#pragma once

/**
 * @file TestDataList.hpp
 * @author Timothée David--Cléris (timothee.david--cleris@ens-lyon.fr)
 * @brief
 */

#include "TestData.hpp"
#include <vector>

namespace shamtest::details {

    /// List of data generated by a test
    struct TestDataList {

        /// Held test data
        std::vector<TestData> test_data;

        // define member function here
        // to register test data

        /// Create a new TestData in this TestDataList and return a reference to it
        [[nodiscard]] inline TestData &new_dataset(std::string name) {
            test_data.push_back(TestData{std::move(name), {}});
            return test_data.back();
        }

        /// Serialize the assertion in JSON
        std::string serialize_json();
        /// Serialize the assertion in binary format
        void serialize(std::basic_stringstream<byte> &stream);
        /// DeSerialize the assertion from binary format
        static TestDataList deserialize(std::basic_stringstream<byte> &reader);
    };

} // namespace shamtest::details
