coverage:
  status:
    project:
      default:
        # Don't fail the status check if coverage decreases.
        informational: true
    patch:
      default:
        # Don't fail the status check if coverage decreases.
        informational: true

comment:
  require_changes: false # always post details even when patch coverage is fully covered
  layout: "header, diff, flags, components"  # show component info in the PR comment # show component info in the PR comment

component_management:

  # Shamrock components (should match the targets declared in src/CMakeLists.txt)
  individual_components:
    - component_id: shamformat
      name: shamformat
      paths:
        - src/shamformat/**

    - component_id: shamterm
      name: shamterm
      paths:
        - src/shamterm/**

    - component_id: shamunits
      name: shamunits
      paths:
        - src/shamunits/**

    - component_id: shambase
      name: shambase
      paths:
        - src/shambase/**

    - component_id: shamcomm
      name: shamcomm
      paths:
        - src/shamcomm/**

    - component_id: shambackends
      name: shambackends
      paths:
        - src/shambackends/**

    - component_id: shammath
      name: shammath
      paths:
        - src/shammath/**

    - component_id: shamalgs
      name: shamalgs
      paths:
        - src/shamalgs/**

    - component_id: shamsys
      name: shamsys
      paths:
        - src/shamsys/**

    - component_id: shamphys
      name: shamphys
      paths:
        - src/shamphys/**

    - component_id: shamcmdopt
      name: shamcmdopt
      paths:
        - src/shamcmdopt/**

    - component_id: shambindings
      name: shambindings
      paths:
        - src/shambindings/**

    - component_id: shamtree
      name: shamtree
      paths:
        - src/shamtree/**

    - component_id: shamlib
      name: shamlib
      paths:
        - src/shamrock/**

    - component_id: shampylib
      name: shampylib
      paths:
        - src/shampylib/**

    - component_id: shammodels_common
      name: shammodels_common
      paths:
        - src/shammodels/common/**

    - component_id: shammodels_zeus
      name: shammodels_zeus
      paths:
        - src/shammodels/zeus/**

    - component_id: shammodels_ramses
      name: shammodels_ramses
      paths:
        - src/shammodels/ramses/**

    - component_id: shammodels_sph
      name: shammodels_sph
      paths:
        - src/shammodels/sph/**

    - component_id: shammodels_gsph
      name: shammodels_gsph
      paths:
        - src/shammodels/gsph/**
