// -------------------------------------------------------//
//
// SHAMROCK code for hydrodynamics
// Copyright (c) 2021-2026 Timothée David--Cléris <tim.shamrock@proton.me>
// SPDX-License-Identifier: CeCILL Free Software License Agreement v2.1
// Shamrock is licensed under the CeCILL 2.1 License, see LICENSE for more information
//
// -------------------------------------------------------//

#pragma once

/**
 * @file kernel_call.hpp
 * @author Timothée David--Cléris (tim.shamrock@proton.me)
 * @brief
 *
 */

#include "shambase/optional.hpp"
#include "shambase/type_traits.hpp"
#include "shambackends/DeviceBuffer.hpp"
#include "shambackends/kernel_call/MultiRef.hpp"
#include "shambackends/kernel_call/MultiRefOpt.hpp"
#include "shambackends/kernel_call/buffer_access_utils.hpp"
#include <functional>
#include <optional>

namespace sham {

    namespace details {

        /// internal implementation of typed_index_kernel_call
        template<class index_t, class RefIn, class RefOut, class Functor>
        void typed_index_kernel_call_lambda(
            sham::DeviceQueue &q,
            RefIn in,
            RefOut in_out,
            index_t n,
            Functor &&kernel_gen,
            SourceLocation &&callsite = SourceLocation{}) {

            __shamrock_stack_entry_with_callsite(callsite);

            if (n == 0) {
                shambase::throw_with_loc<std::runtime_error>("kernel call with : n == 0");
            }

            sham::EventList depends_list;

            auto acc_in     = in.get_read_access(depends_list);
            auto acc_in_out = in_out.get_write_access(depends_list);

            sycl::event e;

            // unpack the tuples of accessors
            std::apply(
                [&](auto &...__acc_in) {
                    std::apply(
                        [&](auto &...__acc_in_out) {
                            // submit the kernel generated by the functor
                            e = q.submit(depends_list, kernel_gen(n, __acc_in..., __acc_in_out...));
                        },
                        acc_in_out);
                },
                acc_in);

            in.complete_event_state(e);
            in_out.complete_event_state(e);
        }

        //////////////////////////////////////////////////////////////////////////////
        // Helper types for kernel signature checking (and clean error messages)
        //////////////////////////////////////////////////////////////////////////////

        /// helper type to get the arguments types of the kernel generator
        template<class index_t, class RefIn, class RefOut>
        struct kernel_gen_args {

            using args_types = decltype(std::tuple_cat(
                std::tuple<index_t>{},

                std::declval<decltype(std::declval<RefIn>().get_read_access(
                    std::declval<sham::EventList &>()))>(),

                std::declval<decltype(std::declval<RefOut>().get_write_access(
                    std::declval<sham::EventList &>()))>()));
        };

        /// Helper to extract the function signature from a tuple of types
        template<typename Tuple>
        struct tuple_to_signature;

        template<typename... Ts>
        struct tuple_to_signature<std::tuple<Ts...>> {
            using type = void(Ts...);
        };

        /// Trick to name the error message if we want to use it
        template<typename Signature>
        struct expected_kernel_signature;

        template<typename Ret, typename... Ts>
        struct expected_kernel_signature<Ret(Ts...)> {};

        /// The expected signature of the kernel generator
        template<class index_t, class RefIn, class RefOut>
        using kernel_expected_signature = expected_kernel_signature<typename tuple_to_signature<
            typename kernel_gen_args<index_t, RefIn, RefOut>::args_types>::type>;

        /// Helper to check if the functor is invocable with the expected signature
        template<typename F, typename Signature>
        struct is_kernel_invocable;

        template<typename F, typename Ret, typename... Ts>
        struct is_kernel_invocable<F, expected_kernel_signature<Ret(Ts...)>>
            : std::bool_constant<std::invocable<F, Ts...>> {};

        /// Concept to check if the functor is invocable with the expected signature
        /// can be used by doing :
        /// requires kernel_invocable<Functor, kernel_expected_signature<index_t, RefIn, RefOut>>
        template<typename F, typename Signature>
        concept kernel_invocable = is_kernel_invocable<F, Signature>::value;

        /// Unwrap `expected_kernel_signature<Ret(Ts...)>` to the raw function type `Ret(Ts...)`
        /// so diagnostics can print the signature without an extra template nesting level.
        template<typename Signature>
        struct expected_kernel_fn_type;

        template<typename Ret, typename... Ts>
        struct expected_kernel_fn_type<expected_kernel_signature<Ret(Ts...)>> {
            using type = Ret(Ts...);
        };

        /// Always-false flag parameterized by the expected function type (shown in static_assert).
        template<class ExpectedFnSignature>
        inline constexpr bool matches_expected_kernel_signature = false;

        /// internal implementation of typed_index_kernel_call
        ///
        /// Signature mismatches are reported with a single static_assert that embeds the raw
        /// expected function type. The body is gated by if constexpr so a bad functor does not
        /// cascade into further template errors.
        template<class index_t, class RefIn, class RefOut, class Functor>
        void typed_index_kernel_call(
            sham::DeviceQueue &q,
            RefIn in,
            RefOut in_out,
            index_t n,
            Functor &&func,
            SourceLocation &&callsite = SourceLocation{}) {

            using expected_sig = kernel_expected_signature<index_t, RefIn, RefOut>;

            if constexpr (is_kernel_invocable<Functor, expected_sig>::value) {
                __shamrock_log_callsite(callsite);

                typed_index_kernel_call_lambda(
                    q,
                    in,
                    in_out,
                    n,
                    [func
                     = std::forward<Functor>(func)](u32 n, auto... __acc_in, auto... __acc_in_out) {
                        return [=](sycl::handler &cgh) {
                            cgh.parallel_for(sycl::range<1>{n}, [=](sycl::item<1> item) {
                                func(index_t(item.get_linear_id()), __acc_in..., __acc_in_out...);
                            });
                        };
                    });
            } else {
                static_assert(
                    matches_expected_kernel_signature<
                        typename expected_kernel_fn_type<expected_sig>::type>,
                    "Kernel functor is not invocable with the expected signature; see "
                    "matches_expected_kernel_signature<void(...)> for the required argument list.");
            }
        }
    } // namespace details

    /**
     * @brief Submit a kernel to a SYCL queue.
     *
     * # Automatic kernel dependency handling
     *
     * This pr introduce a kernel call function to automatically forward buffer pointers and handle
     * events, the ideal usage would be :
     * @code
     * kernel_call(queue, input buf ..., out buf ..., element count, kernel);
     * @endcode
     *
     * However, c++ does not allow multiple parameter pack so a `MultiRef` wrapper is introduced,
     * the call then looks like:
     * @code
     * kernel_call(queue, MultiRef{input buf ...}, MultiRef{out buf ...}, element count, kernel);
     * @endcode
     *
     * This allows the flexibility of forwarding more complex structures, as well as optional
     * buffers.
     *
     * ## Standard usage
     * In a normal usage it is used like so
     * @code {.cpp}
     * sham::DeviceBuffer<Tscal> &buf_P  = storage.pressure.get().get_buf_check(id);
     * sham::DeviceBuffer<Tscal> &buf_cs = storage.soundspeed.get().get_buf_check(id);
     *
     * sham::DeviceBuffer<Tscal> &buf_h = mpdat.pdat.get_field_buf_ref<Tscal>(ihpart_interf);
     * sham::DeviceBuffer<Tscal> &buf_uint = mpdat.pdat.get_field_buf_ref<Tscal>(iuint_interf);
     *
     * sham::kernel_call(q,
     *     sham::MultiRef{buf_h, buf_uint},
     *     sham::MultiRef{buf_P, buf_cs},
     *     mpdat.total_elements,
     *     [pmass = gpart_mass, gamma = eos_config->gamma](
     *         u32 i,
     *         const Tscal *h,
     *         const Tscal *U,
     *         Tscal *P,
     *         Tscal *cs) {
     *         Tscal rho_a = rho(i);
     *         Tscal P_a   = EOS::pressure(gamma, rho_a, U[i]);
     *         Tscal cs_a  = EOS::cs_from_p(gamma, rho_a, P_a);
     *         P[i]        = P_a;
     *         cs[i]       = cs_a;
     *     });
     * @endcode
     *
     * Under the hood read and write access as well as complete_event_state will be called
     * implicitly thanks to the template resolution.
     *
     * ## Complex accessors
     * Since `sham::kernel_call` simply call get_read_access, get_write_access,
     * complete_event_state. We can pass a complex struct instead of a `DeviceBuffer` as long as it
     * defines similar accessor functions.
     *
     * Example :
     * @code {.cpp}
     * sham::DeviceBuffer<Tscal> &buf_P  = storage.pressure.get().get_buf_check(id);
     * sham::DeviceBuffer<Tscal> &buf_cs = storage.soundspeed.get().get_buf_check(id);
     *
     * sham::DeviceBuffer<Tscal> &buf_h = mpdat.pdat.get_field_buf_ref<Tscal>(ihpart_interf);
     * sham::DeviceBuffer<Tscal> &buf_uint = mpdat.pdat.get_field_buf_ref<Tscal>(iuint_interf);
     *
     * struct RhoGetter {
     *     sham::DeviceBuffer<Tscal> &buf_h;
     *     Tscal pmass;
     *     Tscal hfact;
     *
     *     struct accessed {
     *         const Tscal *h;
     *         Tscal pmass;
     *         Tscal hfact;
     *
     *         Tscal operator()(u32 i) const {
     *             using namespace shamrock::sph;
     *             return rho_h(pmass, h[i], hfact);
     *         }
     *     };
     *
     *     accessed get_read_access(sham::EventList &depends_list) {
     *         auto h = buf_h.get_read_access(depends_list);
     *         return accessed{h, pmass, hfact};
     *     }
     *
     *     void complete_event_state(sycl::event e) { buf_h.complete_event_state(e);}
     * };
     *
     * RhoGetter rho_getter{buf_h, gpart_mass, Kernel::hfactd};
     *
     * sham::kernel_call(q,
     *     sham::MultiRef{rho_getter, buf_uint},
     *     sham::MultiRef{buf_P, buf_cs},
     *     mpdat.total_elements,
     *     [gamma = eos_config->gamma](
     *         u32 i,
     *         const typename RhoGetter::accessed rho,
     *         const Tscal *U,
     *         Tscal *P,
     *         Tscal *cs) {
     *         Tscal rho_a = rho(i);
     *         Tscal P_a   = EOS::pressure(gamma, rho_a, U[i]);
     *         Tscal cs_a  = EOS::cs_from_p(gamma, rho_a, P_a);
     *         P[i]        = P_a;
     *         cs[i]       = cs_a;
     *     });
     * @endcode
     *
     * ## Optional arguments
     * Another type of `MultiRef` called `MultiRefOpt` can be introduced to pass optional buffers to
     * have buffer specialization thanks to dead argument elimination.
     *
     * It can be used as follows:
     * @code {.cpp}
     * sham::DeviceBuffer<Tscal> &buf_P  = storage.pressure.get().get_buf_check(id);
     * sham::DeviceBuffer<Tscal> &buf_cs = storage.soundspeed.get().get_buf_check(id);
     *
     * sham::DeviceBuffer<Tscal> &buf_h = mpdat.pdat.get_field_buf_ref<Tscal>(ihpart_interf);
     * sham::DeviceBuffer<Tscal> &buf_uint = mpdat.pdat.get_field_buf_ref<Tscal>(iuint_interf);
     *
     * auto get_eps = [&]() {
     *     if constexpr (is_monofluid) {
     *         sham::DeviceBuffer<Tscal> &buf_epsilon
     *             = mpdat.pdat.get_field_buf_ref<Tscal>(ihpart_interf);
     *         return to_opt_ref(buf_epsilon);
     *     } else {
     *         return empty_buf_ref<Tscal>();
     *     }
     * };
     *
     * sham::kernel_call(q,
     *     sham::MultiRefOpt{buf_h, buf_uint, get_eps()},
     *     sham::MultiRef{buf_P, buf_cs},
     *     mpdat.total_elements,
     *     [pmass = gpart_mass, gamma = eos_config->gamma](
     *         u32 i,
     *         const Tscal *h,
     *         const Tscal *U,
     *         const Tscal *epsilon, // set to nullptr if not is_monofluid
     *         Tscal *P,
     *         Tscal *cs) {
     *         auto rho = [&]() {
     *             using namespace shamrock::sph;
     *             if constexpr (is_monofluid) {
     *                 return (1 - epsilon[i]) * rho_h(pmass, h[i], Kernel::hfactd);
     *             } else {
     *                 return rho_h(pmass, h[i], Kernel::hfactd);
     *             }
     *         };
     *
     *         Tscal rho_a = rho();
     *         Tscal P_a   = EOS::pressure(gamma, rho_a, U[i]);
     *         Tscal cs_a  = EOS::cs_from_p(gamma, rho_a, P_a);
     *         P[i]        = P_a;
     *         cs[i]       = cs_a;
     *     });
     * @endcode
     *
     * @param q The SYCL queue to submit the kernel to.
     * @param in The input buffer or MultiRef or MultiRefOpt.
     * @param in_out The input/output buffer or MultiRef or MultiRefOpt.
     * @param n The number of thread to launch.
     * @param func The functor to call for each thread launched.
     */
    template<class RefIn, class RefOut, class Functor>
    void kernel_call(
        sham::DeviceQueue &q,
        RefIn in,
        RefOut in_out,
        u32 n,
        Functor &&func,
        SourceLocation &&callsite = SourceLocation{}) {

        __shamrock_log_callsite(callsite);

        details::typed_index_kernel_call<u32, RefIn, RefOut>(
            q, in, in_out, n, std::forward<Functor>(func));
    }

    /// u64 indexed variant of kernel_call
    template<class RefIn, class RefOut, class Functor>
    void kernel_call_u64(
        sham::DeviceQueue &q,
        RefIn in,
        RefOut in_out,
        u64 n,
        Functor &&func,
        SourceLocation &&callsite = SourceLocation{}) {

        __shamrock_log_callsite(callsite);

        details::typed_index_kernel_call<u64, RefIn, RefOut>(
            q, in, in_out, n, std::forward<Functor>(func));
    }

    // version where one supplies a kernel generator in the form of [&](sycl::handler &cgh) { ... }
    template<class RefIn, class RefOut, class Functor>
    void kernel_call_hndl(
        sham::DeviceQueue &q,
        RefIn in,
        RefOut in_out,
        u32 n,
        Functor &&kernel_gen,
        SourceLocation &&callsite = SourceLocation{}) {

        __shamrock_log_callsite(callsite);

        details::typed_index_kernel_call_lambda<u32, RefIn, RefOut>(
            q, in, in_out, n, std::forward<Functor>(kernel_gen));
    }

    /// u64 indexed variant of kernel_call_hndl
    template<class RefIn, class RefOut, class Functor>
    void kernel_call_hndl_u64(
        sham::DeviceQueue &q,
        RefIn in,
        RefOut in_out,
        u64 n,
        Functor &&kernel_gen,
        SourceLocation &&callsite = SourceLocation{}) {

        __shamrock_log_callsite(callsite);

        details::typed_index_kernel_call_lambda<u64, RefIn, RefOut>(
            q, in, in_out, n, std::forward<Functor>(kernel_gen));
    }

} // namespace sham
