name: On Schedule


on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    # At 02:00 on Monday, Wednesday, and Friday.
    - cron:  '0 2 * * 1,3,5'


jobs:

  check_codecov_secret:
    name: Check Codecov secret
    runs-on: ubuntu-latest
    steps:
      - name: Debug Codecov token
        run: |
          if [ -z "${{ secrets.CODECOV_TOKEN }}" ]; then
            echo "TOKEN IS EMPTY"
            exit 1
          else
            echo "TOKEN EXISTS"
          fi
  main_workflow:
    name: CI
    uses: ./.github/workflows/main_workflow.yml
    with:
      run_build_push_docker: true
      light_ci: false
