name: Acpp/clang (Coverage)

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        description: "Codecov upload token"
        required: false

jobs:

  shamrock_acpp_omp_debug_coverage:
    name: AdaptiveCpp coverage omp clang-${{ matrix.clang }}
    runs-on: [self-hosted, docker-runner]

    container:
      image: ${{ matrix.container }}

    strategy:
      matrix:
        include:
          - clang: 20
            container: ghcr.io/shamrock-code/shamrock-ci:ubuntu22

    timeout-minutes: 120
    steps:

      - name: Debug Codecov token
        if: ${{ github.event_name == 'push' }}
        run: |
          if [ -z "${{ secrets.CODECOV_TOKEN }}" ]; then
            echo "TOKEN IS EMPTY"
            exit 1
          else
            echo "TOKEN EXISTS"
          fi

      #### Checkout part ####
      # Checkout merge commit if PR otherwise default
      - name: Reconfigure git
        run: |
          git config --global --add safe.directory '*'
          git config --global --list
      - uses: actions/checkout@v4
        if: github.event_name == 'pull_request_target'
        with:
          fetch-depth: 0
          submodules: recursive
          ref: "refs/pull/${{ github.event.number }}/merge"

      - uses: actions/checkout@v4
        if: github.event_name != 'pull_request_target'
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Show diff against main
        if: github.event_name == 'pull_request_target'
        run: git diff ${{ github.event.pull_request.base.sha }} HEAD
      #### End Checkout part ####

      - name: ls local
        run: ls -la

      - name: install LLVM
        run: |
          echo "APT::Acquire::Retries \"10\";" | sudo tee -a /etc/apt/apt.conf.d/80-retries
          sudo apt update && \
          ./tools/apt_install_llvm.sh ${{matrix.clang}}

      - uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-coverage-acpp
          verbose: 2

      - name: Configure ccache
        shell: bash
        run: |
          echo " ----- ccache configuration ----- "
          echo " Old configuration: "
          ccache -p
          echo " ----- New configuration:   ----- "
          ccache -o compiler_check='%compiler% -dumpmachine; %compiler% -dumpversion'
          ccache -p
          echo " ----- ccache configuration done ----- "

      - name: configure Shamrock
        run: |
          ./env/new-env --machine debian-generic.acpp --builddir acpp_omp_debug --type coverage -- --backend omp

      - name: Configure
        shell: bash # In docker container github action default to sh
        run: |
          cd acpp_omp_debug
          source ./activate && shamconfigure

      - name: Build
        shell: bash # In docker container github action default to sh
        run: |
          cd acpp_omp_debug
          export NINJA_STATUS="[%f/%t j=%r] "
          source ./activate && shammake

      - name: Pull reference files
        run: |
          cd acpp_omp_debug
          git clone https://github.com/Shamrock-code/reference-files.git

      - name: run Shamrock test suite
        run: |
          cd acpp_omp_debug
          export SYCLCFG=0:0
          export MPIARGS="--allow-run-as-root --bind-to socket:overload-allowed --oversubscribe"
          ../tools/test_sequence.sh

      - name: merge coverage reports
        run: |
          cd acpp_omp_debug
          ls -la
          llvm-profdata-${{matrix.clang}} merge -sparse utests_* -o utests.profdata

      - name: make coverage reports
        run: |
          cd acpp_omp_debug

          # Txt output
          llvm-cov-${{matrix.clang}} report shamrock_test \
              -instr-profile=utests.profdata \
              -ignore-filename-regex=".*external/|.*src/tests/|.*src/shamtest/|.*\main_test.cpp|.*\main.cpp|.*\aliases.hpp" \
              > coverage_list.txt

          # HTML website for doc
          llvm-cov-${{matrix.clang}} show shamrock_test \
              -instr-profile=utests.profdata \
              -format=html \
              -output-dir=out_cov \
              -Xdemangler c++filt \
              -Xdemangler -n \
              -ignore-filename-regex=".*external/|.*src/tests/|.*src/shamtest/|.*\main_test.cpp|.*\main.cpp|.*\aliases.hpp"

          # export LCOV for Codecov
          llvm-cov-${{matrix.clang}} export shamrock_test \
              -instr-profile=utests.profdata \
              -format=lcov \
              -ignore-filename-regex=".*external/|.*src/tests/|.*src/shamtest/|.*\main_test.cpp|.*\main.cpp|.*\aliases.hpp" \
              > coverage.info

      - name: print coverage
        run: |
          cd acpp_omp_debug
          llvm-cov-${{matrix.clang}} report shamrock_test -instr-profile=utests.profdata \
              -ignore-filename-regex=".*external/|.*src/tests/|.*src/shamtest/|.*\main_test.cpp|.*\main.cpp|.*\aliases.hpp"\

      - name: Archive code coverage results 1
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-list-acpp_omp_debug
          path: acpp_omp_debug/coverage_list.txt

      - name: Archive code coverage results 2
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report-acpp_omp_debug
          path: acpp_omp_debug/out_cov/

      - name: Upload coverage reports to Codecov (push)
        if: github.event_name == 'push'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: acpp_omp_debug/coverage.info
          fail_ci_if_error: false
          verbose: true

      - name: Upload coverage reports to Codecov (not push)
        if: github.event_name != 'push'
        uses: codecov/codecov-action@v5
        with:
          files: acpp_omp_debug/coverage.info
          fail_ci_if_error: false
          verbose: true
